name: Deploy the Go Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ssh key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to RASPI (docs in whatsapp)
        run: |
          ssh -o StrictHostKeyChecking=no pi@nogler.ddns.net -ip << 'EOF'
            echo "Stopping Go Server..."
            sudo systemctl stop go-app || true  # Ignore errors if not running

            echo "Updating repository..."
            cd /home/pi/psoft/Backend
            git reset --hard  # Ensure clean state
            git pull origin main

            echo "Restarting Go Server..."
            sudo systemctl restart go-app

            echo "Deployment complete."
          EOF
